

services:
  mongo:
    image: mongo:latest
    container_name: practitioner-notes-mongo
    ports:
      - "27017:27017"
    networks:
      - mediscreen-network-main
    volumes:
     - ./init-scripts:/docker-entrypoint-initdb.d
    environment:
     MONGO_INITDB_DATABASE: practitionernotes
  practitioner-notes:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: practitioner-notes-app
    ports:
      - "9095:9095"
    depends_on:
      - mongo
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/practitionernotes
    networks:
      - mediscreen-network-main
#      - mediscreen-network-pn

networks:
  mediscreen-network-main:
   driver: bridge
 
#   name: mediscreen-network-main
#   external: true

  