services:
  patient-demographic-ui:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: patient-demographic-ui
    ports:
      - "8081:8081"  # Change if needed
    networks:
      - mediscreen-network-ds
    depends_on:
      - patient-demographics

networks:
  mediscreen-network-ds:
    name: mediscreen-network-main
    external: true